version: '3'

services:
    db:
        image: 'mongo'
        ports:
            - "27017:27017"

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        command: node server
        volumes:
            - ./server:/app
        ports:
            - "8500:8500"
        depends_on:
            - db
        stdin_open: true
        tty: true

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        command: sh -c "npm install; npm start"
        volumes:
            - ./client:/app
            - node_modules:/app/node_modules
        ports:
            - "3100:3000"
        depends_on:
            - server
volumes:
    node_modules:
